<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 1 Introduction to R and RStudio | Intermediate Statistics with R</title>
  <meta name="description" content="Open resource textbook for Intermediate Statistics at Montana State University, revised to use tidyverse tools" />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 1 Introduction to R and RStudio | Intermediate Statistics with R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Open resource textbook for Intermediate Statistics at Montana State University, revised to use tidyverse tools" />
  <meta name="github-repo" content="atheobold/intermediate-statistics-tidyverse" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 1 Introduction to R and RStudio | Intermediate Statistics with R" />
  
  <meta name="twitter:description" content="Open resource textbook for Intermediate Statistics at Montana State University, revised to use tidyverse tools" />
  

<meta name="author" content="Mark C Greenwood, with revisions by Allison Theobold" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="copyright.html"/>
<link rel="next" href="chapter2.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="css/oistyle.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Intermediate Statistics with R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#textbook-overview"><i class="fa fa-check"></i>Textbook overview</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#statistical-computing"><i class="fa fa-check"></i>Statistical computing</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#getting-rstudio"><i class="fa fa-check"></i>Getting RStudio</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#acknowledgements"><i class="fa fa-check"></i>Acknowledgements</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="about-the-authors.html"><a href="about-the-authors.html"><i class="fa fa-check"></i>About the Authors</a><ul>
<li class="chapter" data-level="" data-path="about-the-authors.html"><a href="about-the-authors.html#tidyverse-update-author"><i class="fa fa-check"></i>Tidyverse Update Author</a></li>
<li class="chapter" data-level="" data-path="about-the-authors.html"><a href="about-the-authors.html#intermediate-statistics-with-r-author"><i class="fa fa-check"></i>Intermediate Statistics with R Author</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="copyright.html"><a href="copyright.html"><i class="fa fa-check"></i>Copyright</a></li>
<li class="chapter" data-level="1" data-path="chapter1.html"><a href="chapter1.html"><i class="fa fa-check"></i><b>1</b> Introduction to <code>R</code> and RStudio</a><ul>
<li class="chapter" data-level="1.1" data-path="chapter1.html"><a href="chapter1.html#section1-1"><i class="fa fa-check"></i><b>1.1</b> Overview of Methods</a></li>
<li class="chapter" data-level="1.2" data-path="chapter1.html"><a href="chapter1.html#section1-2"><i class="fa fa-check"></i><b>1.2</b> Getting Started in <code>R</code></a><ul>
<li class="chapter" data-level="1.2.1" data-path="chapter1.html"><a href="chapter1.html#using-r-as-a-big-calculator"><i class="fa fa-check"></i><b>1.2.1</b> Using <code>R</code> as a Big Calculator</a></li>
<li class="chapter" data-level="1.2.2" data-path="chapter1.html"><a href="chapter1.html#functions-and-their-arguments"><i class="fa fa-check"></i><b>1.2.2</b> Functions and Their Arguments</a></li>
<li class="chapter" data-level="1.2.3" data-path="chapter1.html"><a href="chapter1.html#missing-values"><i class="fa fa-check"></i><b>1.2.3</b> Missing Values</a></li>
<li class="chapter" data-level="1.2.4" data-path="chapter1.html"><a href="chapter1.html#packages-in-r"><i class="fa fa-check"></i><b>1.2.4</b> Packages in <code>R</code></a></li>
<li class="chapter" data-level="1.2.5" data-path="chapter1.html"><a href="chapter1.html#r-markdown-documents-for-reproducibilty"><i class="fa fa-check"></i><b>1.2.5</b> R Markdown Documents for Reproducibilty</a></li>
<li class="chapter" data-level="1.2.6" data-path="chapter1.html"><a href="chapter1.html#importing-data-into-r"><i class="fa fa-check"></i><b>1.2.6</b> Importing Data into <code>R</code></a></li>
<li class="chapter" data-level="1.2.7" data-path="chapter1.html"><a href="chapter1.html#inspecting-data"><i class="fa fa-check"></i><b>1.2.7</b> Inspecting Data</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="chapter1.html"><a href="chapter1.html#section1-3"><i class="fa fa-check"></i><b>1.3</b> Introduction to Data Summarization</a><ul>
<li class="chapter" data-level="1.3.1" data-path="chapter1.html"><a href="chapter1.html#the-pipe-operator"><i class="fa fa-check"></i><b>1.3.1</b> The Pipe Operator</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="chapter1.html"><a href="chapter1.html#section1-4"><i class="fa fa-check"></i><b>1.4</b> Introduction to Data Visualization in <code>R</code></a><ul>
<li class="chapter" data-level="1.4.1" data-path="chapter1.html"><a href="chapter1.html#histogram"><i class="fa fa-check"></i><b>1.4.1</b> Histogram</a></li>
<li class="chapter" data-level="1.4.2" data-path="chapter1.html"><a href="chapter1.html#boxplot"><i class="fa fa-check"></i><b>1.4.2</b> Boxplot</a></li>
<li class="chapter" data-level="1.4.3" data-path="chapter1.html"><a href="chapter1.html#density-plot"><i class="fa fa-check"></i><b>1.4.3</b> Density Plot</a></li>
<li class="chapter" data-level="1.4.4" data-path="chapter1.html"><a href="chapter1.html#recap"><i class="fa fa-check"></i><b>1.4.4</b> Recap</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="chapter1.html"><a href="chapter1.html#section1-5"><i class="fa fa-check"></i><b>1.5</b> Chapter Summary</a></li>
<li class="chapter" data-level="1.6" data-path="chapter1.html"><a href="chapter1.html#section1-6"><i class="fa fa-check"></i><b>1.6</b> Summary of Important R code</a></li>
<li class="chapter" data-level="1.7" data-path="chapter1.html"><a href="chapter1.html#section1-7"><i class="fa fa-check"></i><b>1.7</b> Practice Problems</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="chapter2.html"><a href="chapter2.html"><i class="fa fa-check"></i><b>2</b> (R)e-Introduction to statistics</a><ul>
<li class="chapter" data-level="2.1" data-path="chapter2.html"><a href="chapter2.html#section2-1"><i class="fa fa-check"></i><b>2.1</b> Histograms, boxplots, and density curves</a></li>
<li class="chapter" data-level="2.2" data-path="chapter2.html"><a href="chapter2.html#section2-2"><i class="fa fa-check"></i><b>2.2</b> Pirate-plots</a></li>
<li class="chapter" data-level="2.3" data-path="chapter2.html"><a href="chapter2.html#section2-3"><i class="fa fa-check"></i><b>2.3</b> Models, hypotheses, and permutations for the two sample mean situation</a></li>
<li class="chapter" data-level="2.4" data-path="chapter2.html"><a href="chapter2.html#section2-4"><i class="fa fa-check"></i><b>2.4</b> Permutation testing for the two sample mean situation</a></li>
<li class="chapter" data-level="2.5" data-path="chapter2.html"><a href="chapter2.html#section2-5"><i class="fa fa-check"></i><b>2.5</b> Hypothesis testing (general)</a></li>
<li class="chapter" data-level="2.6" data-path="chapter2.html"><a href="chapter2.html#section2-6"><i class="fa fa-check"></i><b>2.6</b> Connecting randomization (nonparametric) and parametric tests</a></li>
<li class="chapter" data-level="2.7" data-path="chapter2.html"><a href="chapter2.html#section2-7"><i class="fa fa-check"></i><b>2.7</b> Second example of permutation tests</a></li>
<li class="chapter" data-level="2.8" data-path="chapter2.html"><a href="chapter2.html#section2-8"><i class="fa fa-check"></i><b>2.8</b> Reproducibility Crisis: Moving beyond p &lt; 0.05, publication bias, and multiple testing issues</a></li>
<li class="chapter" data-level="2.9" data-path="chapter2.html"><a href="chapter2.html#section2-9"><i class="fa fa-check"></i><b>2.9</b> Confidence intervals and bootstrapping</a></li>
<li class="chapter" data-level="2.10" data-path="chapter2.html"><a href="chapter2.html#section2-10"><i class="fa fa-check"></i><b>2.10</b> Bootstrap confidence intervals for difference in GPAs</a></li>
<li class="chapter" data-level="2.11" data-path="chapter2.html"><a href="chapter2.html#section2-11"><i class="fa fa-check"></i><b>2.11</b> Chapter summary</a></li>
<li class="chapter" data-level="2.12" data-path="chapter2.html"><a href="chapter2.html#section2-12"><i class="fa fa-check"></i><b>2.12</b> Summary of important R code</a></li>
<li class="chapter" data-level="2.13" data-path="chapter2.html"><a href="chapter2.html#section2-13"><i class="fa fa-check"></i><b>2.13</b> Practice problems</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="chapter3.html"><a href="chapter3.html"><i class="fa fa-check"></i><b>3</b> One-Way ANOVA</a><ul>
<li class="chapter" data-level="3.1" data-path="chapter3.html"><a href="chapter3.html#section3-1"><i class="fa fa-check"></i><b>3.1</b> Situation</a></li>
<li class="chapter" data-level="3.2" data-path="chapter3.html"><a href="chapter3.html#section3-2"><i class="fa fa-check"></i><b>3.2</b> Linear model for One-Way ANOVA (cell means and reference-coding)</a></li>
<li class="chapter" data-level="3.3" data-path="chapter3.html"><a href="chapter3.html#section3-3"><i class="fa fa-check"></i><b>3.3</b> One-Way ANOVA Sums of Squares, Mean Squares, and F-test</a></li>
<li class="chapter" data-level="3.4" data-path="chapter3.html"><a href="chapter3.html#section3-4"><i class="fa fa-check"></i><b>3.4</b> ANOVA model diagnostics including QQ-plots</a></li>
<li class="chapter" data-level="3.5" data-path="chapter3.html"><a href="chapter3.html#section3-5"><i class="fa fa-check"></i><b>3.5</b> Guinea pig tooth growth One-Way ANOVA example</a></li>
<li class="chapter" data-level="3.6" data-path="chapter3.html"><a href="chapter3.html#section3-6"><i class="fa fa-check"></i><b>3.6</b> Multiple (pair-wise) comparisons using Tukey’s HSD and the compact letter display</a></li>
<li class="chapter" data-level="3.7" data-path="chapter3.html"><a href="chapter3.html#section3-7"><i class="fa fa-check"></i><b>3.7</b> Pair-wise comparisons for the Overtake data</a></li>
<li class="chapter" data-level="3.8" data-path="chapter3.html"><a href="chapter3.html#section3-8"><i class="fa fa-check"></i><b>3.8</b> Chapter summary</a></li>
<li class="chapter" data-level="3.9" data-path="chapter3.html"><a href="chapter3.html#section3-9"><i class="fa fa-check"></i><b>3.9</b> Summary of important R code</a></li>
<li class="chapter" data-level="3.10" data-path="chapter3.html"><a href="chapter3.html#section3-10"><i class="fa fa-check"></i><b>3.10</b> Practice problems</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Intermediate Statistics with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="chapter1" class="section level1">
<h1><span class="header-section-number">Chapter 1</span> Introduction to <code>R</code> and RStudio</h1>
<div class="chapterintro">
<p>Scientists seek to answer questions using rigorous methods and careful
observations. These observations – collected from the likes of field notes,
surveys, and experiments – form the backbone of a statistical investigation and
are called data. Statistics is the study of how best to collect, analyze, and
draw conclusions from data, and in this first chapter, we focus on both the
properties of data and on the collection of data.
- <em>Introduction to Modern Statistics</em>, Mine Çetinkaya-Rundel &amp; Jo Hardin</p>
</div>
<p>This book is designed primarily for use in a second semester
statistics course although it can also be
useful for researchers needing a quick review or ideas for using <code>R</code> for the
methods discussed in the text. As a text primarily designed for a second
statistics course, it presumes that you have had an introductory statistics
course. There are now many different varieties of introductory statistics from
traditional, formula-based courses (called “consensus” curriculum courses) to
more modern, computational-intensive courses that use randomization ideas to try to
enhance learning of basic statistical methods. We are not going to presume that
you have had a particular “flavor” of introductory statistics or that you had
your introductory statistics out of a particular text, just that you have had a
course that tried to introduce you to the basic terminology and ideas
underpinning statistical reasoning. We would expect that you are familiar with
the logic (or sometimes illogic) of hypothesis testing including null and
alternative hypothesis  and confidence interval
 construction and interpretation,
and that you have seen all of these concepts in a couple of basic situations. We
start with a review of these ideas in one and two group situations with a
quantitative response, something that you likely have seen before.</p>
<p>This text covers a wide array of statistical tools that are connected
through situation, methods used, or both. As we explore various techniques, look
for the identifying characteristics of each method – what type of research
questions are being addressed (relationships or group differences, for example)
and what type of variables are being analyzed (quantitative or categorical).
<strong><em>Quantitative variables</em></strong>  are made up of numerical
measurements that have meaningful units attached to them, so that averages of
measurements make sense. For example, averages of student heights is meaningful,
but averages of letter grades are not. <strong><em>Categorical variables</em></strong>
 take on values that are categories or labels, such as
letter grades. Additionally, you will need to carefully identify the
<strong><em>response</em></strong>  and <strong><em>explanatory</em></strong> 
variables, where the study and variable characteristics should suggest which
variables should be used as the explanatory variables which may explain
variation in the response variable. Because this is an intermediate statistics
course, we will start to handle more complex situations (many explanatory
variables), while also providing tools for data wrangling and data visualization,
complementing the more sophisticated statistical models required to handle these
situations.</p>
<div id="section1-1" class="section level2">
<h2><span class="header-section-number">1.1</span> Overview of Methods</h2>
<p>After you are introduced to basic statistical ideas, a wide array of statistical
methods become available. The methods explored here focus on assessing
(estimating and testing for) relationships between variables, sometimes when
controlling for or modifying relationships based on levels of another variable
– which is where statistics gets interesting and really useful. Early
statistical analyses (approximately 100 years ago) were focused on describing a
single variable. Your introductory statistics course should have explored
methods for summarizing, visualizing, and doing inference in
situations with one group or where you were comparing results for two groups of
observations. Now, we get to consider more complicated situations – culminating
in a set of tools for working with multiple explanatory variables, some of
which might be categorical and related to having different groups of subjects
that are being compared. Throughout all of the methods we will cover, it will be
important to retain a focus on how the appropriate statistical analysis depends
on the research question and data collection process as well as the types of
variables measured.</p>
<p>Figure <a href="chapter1.html#fig:Figure1-1">1.1</a> frames the topics we will discuss. Taking a broad
view of the methods we will consider,
there are basically two scenarios – one when the response is quantitative and
one when the response is categorical. Examples of quantitative responses we will
see later involve <em>passing distance of cars for a bicycle rider</em> (in centimeters)
and <em>body fat</em> (percentage). Examples of categorical variables include
<em>improvement</em> (none, some, or marked) in a clinical trial related to arthritis
symptoms or whether a student has turned in copied work (never, done this on an
exam or paper, or both). There are going to be some more nuanced aspects to all
these analyses as the complexity of both sides of Figure <a href="chapter1.html#fig:Figure1-1">1.1</a>
suggest, but note that near the bottom, each tree converges on a single
procedure, using a <strong><em>linear model</em></strong>  for a quantitative
response variable or using a <strong><em>Chi-square test</em></strong> for a categorical response.
 After selecting the appropriate procedure and completing
the necessary technical steps to get results for a
given data set, the final step involves assessing the scope of inference
 and
types of conclusions that are appropriate based on the design of the study.</p>

<div class="figure" style="text-align: center"><span id="fig:Figure1-1"></span>
<img src="01/images/image002.png" alt="Flow chart of data analysis procedures." width="100%" />
<p class="caption">
Figure 1.1: Flow chart of data analysis procedures.
</p>
</div>
<p>We will be spending most of the semester working on methods for quantitative
response variables (the
left side of Figure <a href="chapter1.html#fig:Figure1-1">1.1</a> is covered in Chapters <a href="chapter2.html#chapter2">2</a>,
<a href="chapter3.html#chapter3">3</a>, <a href="#chapter4"><strong>??</strong></a>, <a href="#chapter6"><strong>??</strong></a>, <a href="#chapter7"><strong>??</strong></a>, and
<a href="#chapter8"><strong>??</strong></a>), stepping
over to handle the situation with a categorical response variable in Chapter
<a href="#chapter5"><strong>??</strong></a> (right side of Figure <a href="chapter1.html#fig:Figure1-1">1.1</a>).
Chapter <a href="#chapter9"><strong>??</strong></a> contains case studies
illustrating all the methods discussed previously, providing a final opportunity
to explore additional examples that illustrate how finding a
path through Figure <a href="chapter1.html#fig:Figure1-1">1.1</a> can lead to the appropriate analysis.</p>
<p>The first topics (Chapters <a href="chapter1.html#chapter1">1</a>, and <a href="chapter2.html#chapter2">2</a>) will be
more familiar as we start with single and two group situations
with a quantitative response. In your previous statistics course, you should
have seen methods for estimating and quantifying uncertainty for the mean of a
single group and for differences in the means of two groups. Once we have
briefly reviewed these methods and introduced the statistical software that we
will use throughout the course, we will consider the first new statistical
material in Chapter <a href="chapter3.html#chapter3">3</a>. It involves the situation with a
quantitative response variable where
there are more than 2 groups to compare – this is what we call the <strong><em>One-Way
ANOVA</em></strong> situation. It generalizes the 2-independent sample hypothesis
test to handle situations where more than 2 groups are being studied. When we
learn this method, we will begin discussing model assumptions
 and methods for assessing those assumptions that will be
present in every analysis involving a
quantitative response. The <strong><em>Two-Way ANOVA</em></strong> (Chapter <a href="chapter3.html#chapter3">3</a>)
considers situations with two categorical explanatory variables and a
quantitative response. To make
this somewhat concrete, suppose we are interested in assessing differences in,
say, the <em>yield</em> of wheat from a field based on the amount of <em>fertilizer</em>
applied (none, low, or high) and <em>variety</em> of wheat (two types). Here, <em>yield</em>
is a quantitative response variable that might be measured in bushels per acre
and there are two categorical explanatory variables, <em>fertilizer</em>, with three
levels, and <em>variety</em>, with two levels. In this material, we introduce the idea
of an <strong><em>interaction</em></strong> between the two explanatory variables:
 the relationship between one categorical
variable and the mean of the response changes depending on the levels of the
other categorical variable. For example, extra fertilizer might enhance the
growth of one variety and hinder the growth of another so we would say that
<em>fertilizer</em> has different impacts based on the level of <em>variety</em>. Given this
interaction may or may not actually be present, we will consider two versions
of the model in Two-Way ANOVAs,  what are called the
<strong><em>additive</em></strong>  (no interaction) and the <strong><em>interaction</em></strong>  models.</p>
<p>Following the methods for two categorical variables and a quantitative
response, we explore a method for analyzing data where the response is
categorical, called the <strong><em>Chi-square test</em></strong>
in Chapter <a href="#chapter5"><strong>??</strong></a>. This most closely matches the one-way ANOVA
situation with a single categorical explanatory variable, except now the
response variable is categorical. For example, we will assess whether taking a
drug (vs taking a <strong><em>placebo</em></strong><a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a>)
has an <strong><em>effect</em></strong><a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a> on the type of improvement the subjects
demonstrate. There are two different scenarios
for study design that impact the analysis technique and hypotheses tested in
Chapter <a href="#chapter5"><strong>??</strong></a>. If the explanatory variable reflects the group that
subjects were
obtained from, either through randomization of the treatment level to the
subjects or by taking samples from separate populations, this is called a
<strong><em>Chi-square Homogeneity Test</em></strong>.  It
is also possible to obtain a single sample
from a population and then obtain information on the levels of the explanatory
variable for each
subject. We will analyze these results using what is called a
<strong><em>Chi-square Independence Test</em></strong>. 
They both use the same test statistic but we will use slightly different
graphics and are testing different hypotheses in these two related situations.
Figure <a href="chapter1.html#fig:Figure1-1">1.1</a> also shows that if we had a quantitative explanatory
variable and a categorical response that we could “bin” or create
categories of responses from the quantitative variable to use the Chi-square
testing methods. Alternatively, if we did not create categories from the
quantitative explanatory variable, we would use a <strong>Logistic Regression</strong>.
This type of data model will be covered in additional statistics classes, but
has connections to the linear models discussed in this textbook.</p>
<p>If the predictor and response variables are both quantitative, we start
with scatterplots, correlation,
and <strong><em>simple linear regression</em></strong> models (Chapters <a href="#chapter6"><strong>??</strong></a> and
<a href="#chapter7"><strong>??</strong></a>) – things you should have seen, at least to some degree, in
your introductory statistics course. The biggest differences here will be
the depth of exploration of diagnostics and inferences for this model and
discussions of transformations of variables included in the model.
 If there is more than one explanatory variable, then we
say that we are performing a <strong><em>multiple linear regression</em></strong>
(Chapter <a href="#chapter8"><strong>??</strong></a>) – where the “multiple” part of the procedure reflects
the inclusion of more than one explanatory variable in the model. We use the
same procedure if we have a mix of categorical and quantitative predictor
variables but there are some new issues in setting up the models and
interpreting the coefficients that we will need to consider. In the situation
with one categorical predictor and one quantitative predictor, we will revisit
the idea of an interaction. 
An interaction allows us to consider situations
where the estimated relationship between a quantitative predictor and the
mean response
varies across different levels of the categorical variable. In Chapter
<a href="#chapter9"><strong>??</strong></a>, connections among all the methods used for quantitative
responses are discussed, showing that they all have the same foundation,
because they are all linear models . We also show how the
methods discussed can be applied to a suite of new problems using a set of case
studies and how that relates to further extensions of the methods.</p>
<p>By the end of Chapter <a href="#chapter9"><strong>??</strong></a> you should be able to identify,
perform using the statistical software <code>R</code> <span class="citation">(R Core Team <a href="#ref-R-base" role="doc-biblioref">2020</a>)</span>, and interpret the results
from each of these methods. There
is a lot to learn, but many of the tools for using <code>R</code> and interpreting results
of the analyses accumulate and repeat throughout the textbook. If you work hard
to understand the initial methods, it will help you when the methods get more
complicated. You will likely feel like you are just starting to learn how to
use <code>R</code> at the end of the semester and for learning a programming language that
is a big accomplishment! We will be taking you on the first steps of a
potentially long journey and it is up to you to decide how much further you
want to go with learning the software for wrangling, visualizing, and modeling
data.</p>
<p>All the methods you will learn require you to carefully consider how the
data were collected, how that
pertains to the population of interest, and how that impacts the inferences
that can be made. The <strong><em>scope of inference</em></strong> from the bottom of Figure
<a href="chapter1.html#fig:Figure1-1">1.1</a> is our shorthand term for remembering to think about two
aspects of the study – <strong><em>random assignment</em></strong> and <strong><em>random sampling</em></strong>.
  In a given
situation, you need to use the description of the study to decide if the
explanatory variable was randomly assigned to the study units (this allows for
<strong><em>causal inferences</em></strong>  if differences are detected) or
not (where no causal statements are possible). As an example, think about two
studies, one where students are
randomly assigned to either get tutoring with their statistics course or not
and another where the students are asked at the end of the semester whether
they sought out tutoring or not. Suppose we compare the final grades in the
course for the two groups (tutoring/not) and find a big difference. In the
first study where students were randomly assigned to receive tutoring,
 we can say the tutoring <em>caused</em> the
differences we observed. In the second, we could only say that the tutoring was
<em>associated</em> with differences. Because students self-selected the group they
ended up in, we can’t say that the tutoring caused the differences. The other
aspect of scope of inference concerns random sampling: 
If the data were obtained using a random sampling mechanism, then our inferences
can be safely extended to the population that the sample was taken from.
However, if we have a non-random
sample, our inference can only apply to the sample collected. In the previous
example, the difference would be studying a random sample of students from the
population of, say, Introductory Statistics students at a university versus
studying a sample of students that volunteered for the research project, maybe
for extra credit in the class. We could still randomly assign them to
tutoring/not but the non-random sample would only lead to conclusions about
those students that volunteered. The most powerful scope of inference is when
random assignment is used in a random sample from a population – conclusions
would be about causal impacts that we would expect to happen in the population.</p>
<p>By the end of this material, you should have some <code>R</code> skills to wrangle
data in preparation for analysis, create professional quality data
visualizations, and the ability to fit ANOVA and regression models to data, as
well as to handle Chi-square testing situations. Together, this should prepare
you for future statistics courses or for other
situations where you are expected to be able to identify an appropriate
analysis, do the calculations and required graphics using the data set, and then
effectively communicate interpretations for the methods discussed here.</p>
</div>
<div id="section1-2" class="section level2">
<h2><span class="header-section-number">1.2</span> Getting Started in <code>R</code></h2>
<p>You will need to download the statistical software package called <code>R</code> and an
enhanced interface to R called RStudio <span class="citation">(RStudio Team <a href="#ref-RStudio" role="doc-biblioref">2018</a>)</span>. These are both open source
and free to download and use (and will always be that way). This means that the
skills you learn now can follow you the rest of your life. <code>R</code> is becoming the
primary language of statistics and is being adopted across academia, government,
and businesses to help manage and learn from the growing volume of data being
obtained. Hopefully you will get a sense of some of the power of <code>R</code> in this
book.</p>
<p>The next pages will walk you through the process of getting the software
downloaded and provide you with
an initial experience using RStudio to do things that should look familiar
even though the interface will be a new experience. Do not expect to master <code>R</code>
quickly – it takes years (sorry!) even if you know the statistical methods
being used. We will try to keep all your interactions with <code>R</code> code in a similar
code format and that should help you in learning how to use <code>R</code> as we move
through various methods. We will also often provide you with example code.
Everyone that learns <code>R</code> starts with copying other people’s code and then making
changes for specific applications – so expect to go back to examples from the
text and focus on learning how to modify that code to work for your particular
data set. Only really experienced <code>R</code> users “know” functions without having to
check other resources. After we complete this basic introduction, Chapter
<a href="chapter2.html#chapter2">2</a> starts the exploration of more sophisticated tasks in <code>R</code>,
allowing us to compare quantitative responses from two groups, make some
graphical displays, do hypothesis testing  and create
confidence intervals in a couple of different ways.</p>
<p>You will have two<a href="#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a> downloading activities to complete before
you can do anything more than read this book<a href="#fn4" class="footnote-ref" id="fnref4"><sup>4</sup></a>.
First, you need to download <code>R</code>. It is the engine that will do all the computing
for us, but you will only interact with it once. Go to <a href="http://cran.rstudio.com" class="uri">http://cran.rstudio.com</a>
and click on the “<strong>Download R for…</strong>” button that
corresponds to your operating system. On the next page, click on “<strong>base</strong>” and
then it will take you to a screen to download the most current version of <code>R</code>
that is compiled for your operating system, something like
“<strong>Download R 4.0.2 for Windows</strong>”. Click on that link and then open the file
you downloaded. You will need to select your preferred language (choose English
so your instructor can help you), then hit “<strong>Next</strong>” until it starts to unpack
and install the program (all the base settings will be fine). After you hit
“<strong>Finish</strong>” you will not do anything further with <code>R</code> directly.</p>
<p>Second, you need to download RStudio. RStudio is an integrated
development environment (IDE), which means it provides an enhanced interface that
will make interacting with <code>R</code> less frustrating and allow you to directly create
reports that include the code and output. To download RStudio, go near the
bottom of <a href="https://www.rstudio.com/products/rstudio/download/" class="uri">https://www.rstudio.com/products/rstudio/download/</a> and select the
correct version under “Installers for Supported Platforms” for your operating
system. Download and then install RStudio using the installer. From this point
forward, you should only open RStudio; it provides your interface with <code>R</code>.
Note that both <code>R</code> and RStudio are updated frequently (up to four times a year)
and if you downloaded either more than a few months previously, you should
download the up-to-date versions, especially if something you are trying to do
is not working. Sometimes code will not work in older versions of <code>R</code> and
sometimes old code won’t work in new versions of <code>R</code>.<a href="#fn5" class="footnote-ref" id="fnref5"><sup>5</sup></a></p>

<div class="figure" style="text-align: center"><span id="fig:Figure1-2"></span>
<img src="01/images/fig1-2.png" alt="Initial RStudio layout." width="100%" />
<p class="caption">
Figure 1.2: Initial RStudio layout.
</p>
</div>
<p>To get started, we can complete some basic tasks in <code>R</code> using the
RStudio interface. When you open RStudio, you will see a screen like Figure
<a href="chapter1.html#fig:Figure1-2">1.2</a>. The
added annotation in this and the following screen-grabs is there to help you
get initially oriented to the software interface. R is command-line software –
meaning that in some way or another you have to create code and get it
evaluated, either by entering to be executed (run) in the command prompt (in the
bottom left-hand panel) or by creating a document to store the code, and
executing the code from that file. RStudio makes the management and
execution of that code more efficient than the basic version of <code>R</code>.</p>
<p>In RStudio, the lower left panel is called the “console” window, and is where
all of the action happens. Every time you launch RStudio, it will have the same
text at the top of the console telling you the version of R that you’re running.
Below that information is the <em>prompt</em>, indicated by the <code>&gt;</code> symbol.
As its name suggests, this prompt is really a request: a request for a command.
Initially, interacting with <code>R</code> is all about typing commands and interpreting
the output. These commands and their syntax have evolved over decades
(literally) and now provide what many users feel is a fairly natural way to
access data and organize, describe, and invoke statistical computations.</p>
<p>The upper left panel is for writing, saving, and running your <code>R</code> code either in
<code>R</code> script (.R) files or R Markdown (.Rmd) files. The panel in the upper right
contains your <em>environment</em> as well as a history of the commands that you’ve
previously entered. It also contains the “Import Dataset” button that provides
the easiest way for you to read a data set into <code>R</code> so you can analyze it.</p>
<p>The panel in the lower right contains tabs for browse the <em>files</em> in your
project folder, access <em>help</em> files for <code>R</code> functions, install and manage
<code>R</code> <em>packages</em>, and inspecting visualizations. By default, all data
visualizations you make will appear directly below the code you used to create
them. If you would rather your plots appear in the <em>plots</em> tab, you will need to
change your global options.</p>
<!-- RUNNING CODE -->
<!-- Once you have code available -->
<!-- in this window, the "Run" button will execute the code for the line that your  -->
<!-- cursor is on or for any text that you -->
<!-- have highlighted with your mouse. -->
<!-- Going forward you should refrain from typing your code directly in the console, as this makes it very difficult to remember and reproduce the output you want to reference. -->
<!-- Potentially the most important feature of R Markdown files is that they allow for us to nest our `R` code within a written report. -->
<!-- In an R Markdown file, `R` code appears in a gray box, which we call "code chunks." The R Markdown file knows that the gray box contains `R` code because it begins with three tick marks (\`\`\`), followed by two curly braces that contain a lowercase letter r ({r}). -->
<!-- You've already seen this above! -->
<!-- Instead of typing our `R` code into the console, we encourage you to type any code you produce (final correct answer, or anything you're just trying out) in the `R` code chunk associated with each problem. -->
<!-- You can execute the `R` code you type in these code chunks similar to how you typed code into the console and pressed enter/return. -->
<!-- Within the code chunk there are two ways to execute a line of `R` code: (1) place your cursor on the line on code and press `Ctrl-Enter` or `Cmd-Enter` at the same time, or (2) place your cursor on the line and press the "Run" button in the upper right hand corner of the R Markdown file. -->
<!-- Alternatively, if you wanted to run all of the `R` code in a given code chunk, you can click on the "Play" button in the upper right hand corner of the code chunk (green sideways triangle). -->
<!-- If at any point you need to start over and run all of the code chunks before a specific code chunk, you click on the "Fastforward" button in the upper right hand corner of that code chunk (gray upside down triangle with a bar below). -->
<!-- This will run every code chunk that occurred *before* that code chunk, but *will not* execute the `R` code included in that code chunk. -->
<div id="using-r-as-a-big-calculator" class="section level3">
<h3><span class="header-section-number">1.2.1</span> Using <code>R</code> as a Big Calculator</h3>
<p>As a first interaction with <code>R</code> we can use it as a very powerful
calculator. To do this, click near the command prompt (<code>&gt;</code>) in the lower left
“console” panel, type <code>3+4</code>, and then hit enter. It should look like this:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="chapter1.html#cb1-1"></a><span class="dv">3</span> <span class="op">+</span><span class="st"> </span><span class="dv">4</span></span></code></pre></div>
<pre><code>## [1] 7</code></pre>
<p>You can do more interesting calculations, like finding the mean of a set of
numbers, say -3, 5, 7, and 8, You can do this by adding the numbers up and
dividing by 4:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="chapter1.html#cb3-1"></a>(<span class="op">-</span><span class="dv">3</span> <span class="op">+</span><span class="st"> </span><span class="dv">5</span> <span class="op">+</span><span class="st"> </span><span class="dv">7</span> <span class="op">+</span><span class="st"> </span><span class="dv">8</span>) <span class="op">/</span><span class="st"> </span><span class="dv">4</span></span></code></pre></div>
<pre><code>## [1] 4.25</code></pre>
<p>Note that the parentheses help <code>R</code> to figure out your desired order of
operations. If you drop that grouping, you get a very different (and wrong!)
result:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="chapter1.html#cb5-1"></a><span class="dv">-3</span> <span class="op">+</span><span class="st"> </span><span class="dv">5</span> <span class="op">+</span><span class="st"> </span><span class="dv">7</span> <span class="op">+</span><span class="st"> </span><span class="dv">8</span> <span class="op">/</span><span class="st"> </span><span class="dv">4</span></span></code></pre></div>
<pre><code>## [1] 11</code></pre>
<p>We could the use a formula from introductory statistics to estimate the standard
deviation of this set of numbers, but that gets us away from the reason we are
using <code>R</code>. To use the real power of <code>R</code> in this course, we need to work with
data sets that store observations for our subjects as <em>variables</em>, where
each subject’s information is stored in a different row.</p>
<p>In <code>R</code>, data frames are the <em>de facto</em> data structure, and what
we use for data processing, statistics, and plotting. A data frame is the
representation of data in the format of a table where the columns are vectors
that all have the same length. Data frames are analogous to the more familiar
spreadsheet in programs such as Excel, with one key difference. Because columns
are vectors, each column must contain a single type of data (e.g., characters,
integers, factors). For example, here is a figure depicting a data frame
comprising a numeric, a character, and a logical vector.</p>

<div class="figure" style="text-align: center"><span id="fig:Figure1-3"></span>
<img src="01/images/data-frame.svg" alt="Dataframe structure, from Starting with Data in Data Carpentry’s Social Science curriculum." width="100%" />
<p class="caption">
Figure 1.3: Dataframe structure, from <em>Starting with Data</em> in Data Carpentry’s Social Science curriculum.
</p>
</div>
<p>What we will call “tidy” dataframes, are dictated by three main rules:</p>
<ol style="list-style-type: decimal">
<li>Each variable has its own column</li>
<li>Each observation has its own row</li>
<li>Each value must have its own cell</li>
</ol>
<p>A data frame can be created by hand, but most commonly they are generated by the
functions <code>read_csv()</code> or <code>read_table()</code>. But, we are going to start by working
with the building blocks of datafames: vectors.</p>
<p>Every column of a dataframe contains a vector of observations. To create a
vector we use the concatenate function (<code>c()</code>), which binds together a list of
numbers to form a vector. For example, running the code <code>c(1, 2, 3, 4)</code>, would
output a vector of four numbers, 1, 2, 3, and 4.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="chapter1.html#cb7-1"></a><span class="kw">c</span>(<span class="op">-</span><span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">7</span>, <span class="dv">8</span>)</span></code></pre></div>
<pre><code>## [1] -3  5  7  8</code></pre>
<p>If we would like store this vector into a variable, so we can refer back to it,
we will need to assign it to a variable, like <em><code>variable1</code></em>. To get a vector
stored in a variable we need to use the assignment operator,
<code>&lt;-</code> (read as “is defined to contain”) that assigns the object on the right
into the variable that you are creating on the left.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="chapter1.html#cb9-1"></a>variable1 &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="op">-</span><span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">7</span>, <span class="dv">8</span>)</span></code></pre></div>
<p>In <code>R</code>, the assignment operator, <code>&lt;-</code>, is created by typing a “less than”
symbol <code>&lt;</code> followed by a “minus” sign (<code>-</code>)
<strong>without a space between them</strong>. If you ever want to see what numbers are
residing in an object in <code>R</code>, just type its name in the console and hit <em>enter</em>.
You can see how that variable contains the same information that was initially
generated by <code>c(-3, 5, 7, 8)</code> but is easier to access since we just need the
text for the variable name representing that vector.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="chapter1.html#cb10-1"></a>variable1</span></code></pre></div>
<pre><code>## [1] -3  5  7  8</code></pre>
<div class="important">
<p><code>R</code> is case sensitive! <code>Variable1</code> is not the same as <code>variable1</code>!</p>
</div>
<p>Once we have created a variable, we can start to explore functions we can use
to summarize the contents of the vector.</p>
</div>
<div id="functions-and-their-arguments" class="section level3">
<h3><span class="header-section-number">1.2.2</span> Functions and Their Arguments</h3>
<p>Functions can be thought of as “prepackaged scripts” that automate more
complicated sets of commands. Many functions are what we call “base” functions,
meaning they come automatically installed when you download <code>R</code>. Other
functions are made available by importing <code>R</code> <em>packages</em>, which we will explore
later.</p>
<p>A function usually gets one or more inputs called <em>arguments</em>, and often (but
not always) return a <em>value</em> called an <em>output</em>. A typical example would be the
function <code>mean()</code>. The input (the argument) must be numbers, and the return
value (in fact, the output) is the mean of those numbers. Executing a function
(‘running it’) is called <em>calling</em> the function. An example of a function call
is:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="chapter1.html#cb12-1"></a>mean_var1 &lt;-<span class="st"> </span><span class="kw">mean</span>(variable1)</span></code></pre></div>
<p>Here, the <code>variable1</code> is the input to the <code>mean()</code> function, which the
<code>mean()</code> function uses to calculates the mean of that input, and then returns
the value which is then assigned to the object <code>mean_var1</code>. This function is
very simple, because it only has one required argument.
</p>
<p>The return ‘value’ of a function need not be numerical (like that of <code>mean()</code>),
and it also does not need to be a single item: it can be a set of things, or
even a dataset. We’ll see that when we read data files into <code>R</code>.</p>
<p>Arguments can be anything, not only numbers or filenames, but also other
objects. Exactly what each argument means differs per function, and must be
looked up in the documentation (see below). Some functions take arguments which
may either be specified by the user, or, if left out, take on a <em>default</em> value:
these are called <em>options</em>. Options are typically used to alter the way the
function operates, such as whether it ignores ‘bad values’, or what symbol to
use in a plot. However, if you want something specific, you can specify a value
of your choice which will be used instead of the default.</p>
</div>
<div id="missing-values" class="section level3">
<h3><span class="header-section-number">1.2.3</span> Missing Values</h3>
<p>Let’s explore some of the options in the <code>mean()</code> function. Say your vector
contained missing values, or <code>NA</code> values. If we use the <code>mean()</code> function as
we did before, we will no longer obtain a numeric output if our vector contains
<code>NA</code> values.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="chapter1.html#cb13-1"></a>a &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="op">-</span><span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">7</span>, <span class="dv">8</span>, <span class="ot">NA</span>)</span>
<span id="cb13-2"><a href="chapter1.html#cb13-2"></a><span class="kw">mean</span>(a)</span></code></pre></div>
<pre><code>## [1] NA</code></pre>
<p>When doing operations on numbers, most functions will return <code>NA</code> if the data
you are working with include missing values. This feature makes it harder to
overlook missing data.</p>
<p>If we want to know if we can omit the missing values when finding the mean, we
can look at the help file for the <code>mean()</code> function using <code>?mean</code>.</p>
<p>We see that the <code>mean()</code> function has an <code>na.rm</code> argument that allows for us to
omit <code>NA</code>s when calculating the mean. Notice, this argument defaults to a value
of <code>FALSE</code>, meaning the option is turned off. If you want to turn the option on,
you need to tell <code>R</code> that you wish for <code>na.rm</code> to be <code>TRUE</code>.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="chapter1.html#cb15-1"></a><span class="kw">mean</span>(a, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 4.25</code></pre>
</div>
<div id="packages-in-r" class="section level3">
<h3><span class="header-section-number">1.2.4</span> Packages in <code>R</code></h3>
<p><code>R</code> is an open-source programming language, meaning that users can contribute
packages that make our lives easier, and we can use them for free. Packages in
<code>R</code> provide additional functions and data sets that are not available in the
initial download of <code>R</code> or RStudio.</p>
<p>In this textbook we will use the following packages:</p>
<ul>
<li>The <strong>tidyverse</strong> “umbrella” package which houses a suite of many different
<code>R</code> packages: for data wrangling and data visualization</li>
<li>The <strong>openintro</strong> <code>R</code> package: for data and custom functions with the
OpenIntro resources</li>
</ul>
<p>To install an <code>R</code> package, go to the <strong>Packages</strong> tab in the lower right panel
of RStudio. Click on the <strong>Install</strong> button and then type in the name of the
package in the box (here type in tidyverse and openintro).
 RStudio will try to auto-complete the name
of the package you are typing which should help you make sure you got it typed
correctly. If you are working in a .Rmd file, a highlighted message may show up
on the top of the file to suggest packages to install that are not present –
look for this to help make sure you have the needed packages installed.</p>
<p>After pressing enter/return, a stream of text will begin, communicating the
process <code>R</code> is going through to install the package from the location you
selected when you installed <code>R</code>. If you were not prompted to select a server for
downloading packages when you installed <code>R</code>, RStudio may prompt you to select a
server from which to download; any of them will work.</p>
<p>You will only need to install each <code>R</code> package once on a given computer. If you
ever see a message that <code>R</code> can’t find a package, make sure it appears in the
list in the <strong>Packages</strong> tab. If it doesn’t, repeat the previous steps to
install it.</p>
<p>You only need to <em>install</em> packages once, but you need to <em>load</em> them each time
you relaunch RStudio. We load packages with the <code>library()</code> function.
</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="chapter1.html#cb17-1"></a><span class="kw">library</span>(tidyverse)</span></code></pre></div>
<p>When you load an installed package with <code>library()</code>, you may see a
warning message about versions of the package and versions of
<code>R</code> – this is <em>usually</em> something you can ignore. Other warning messages could
be more ominous for proceeding but before getting too concerned, there are
couple of basic things to check.

First, double check that the package is installed (see previous steps). Second,
check for typographical errors in your code – especially for mis-spellings or
unintended capitalization. If you are still having issues, try repeating the
installation process. Then click on the “<strong>Update</strong>” button to check for
potentially newer versions of packages.</p>
</div>
<div id="r-markdown-documents-for-reproducibilty" class="section level3">
<h3><span class="header-section-number">1.2.5</span> R Markdown Documents for Reproducibilty</h3>
<p>Statisticians (and other scientists) are starting to use R Markdown and
similar methods because they provide what is called “reproducible research”
<span class="citation">(Gandrud <a href="#ref-Gandrud2015" role="doc-biblioref">2015</a>)</span> where all the code and output it produced are available in a
<strong>single</strong> place. This allows different researchers to run and verify
results (so they are “reproducible”) or the original researchers to revisit
their earlier work at a later date and recreate all their results exactly.
Scientific publications are currently encouraging researchers to work in this
way and may someday require it. The term <strong><em>reproducible</em></strong> can also be related
to whether repeated studies get the same result (also called <strong><em>replication</em></strong>)
– further discussion of these terms and the implications for scientific
research are discussed in Chapter <a href="chapter2.html#chapter2">2</a>.</p>
<p>In this course, will be using R Markdown to create reproducible lab reports.
See the following videos describing why and how:</p>
<p><a href="https://youtu.be/lNWVQ2oxNho"><strong>Why use R Markdown for Lab Reports?</strong></a> <iframe width="560" height="315" src="https://www.youtube.com/embed/lNWVQ2oxNho" frameborder="0" allowfullscreen></iframe></p>
<p><a href="https://youtu.be/o0h-eVABe9M"><strong>Using R Markdown for Lab Reports in RStudio</strong></a> <iframe width="560" height="315" src="https://www.youtube.com/embed/o0h-eVABe9M" frameborder="0" allowfullscreen></iframe></p>
<p>In order to get some practice using R Markdown, create a sample document
in this format using File -&gt; New File -&gt; R Markdown… Choose a title for your
file and select the “HTML” option. This will create a new file in the upper left
window. Save that file to your computer, <strong>in a location where you can find it
again</strong>. Then you can use the “Knit” button to have RStudio run the code and
create an HTML document with the results.</p>
<p>Potentially the most important feature of R Markdown files is that
they allow for us to nest our <code>R</code> code within a written report. In an R Markdown
file, <code>R</code> code appears in a gray box, which we call “code chunks.” The R
Markdown file knows that the gray box contains <code>R</code> code because it begins with
three tick marks (<code>```</code>), followed by two curly braces that contain a
lowercase letter r (<code>{r}</code>). You can insert a code chunk using the “Insert”
button in the upper right-hand corner of the R Markdown document, and selecting
the “R” option. Then write your code in between the <code>```{r}</code> and <code>```</code>
lines (it should have gray highlights for those lines and white for the rest of
the portions of the .Rmd document).</p>
<p>Going forward you should refrain from typing your code directly in the console,
as this makes it very difficult to remember and reproduce the output you want to
reference. Instead of typing our <code>R</code> code into the console, we encourage you to
type any code you produce (final correct answer, or anything you’re just trying
out) in the <code>R</code> code chunk associated with each problem.</p>
<p>Once you write some code inside a code chunk, you can execute the <code>R</code> code you
typed in the code chunk similar to how you typed code into the console and
pressed enter/return. Within the code chunk
there are two ways to execute a line of <code>R</code> code: (1) place your cursor on the
line on code and press <kbd>Ctrl</kbd> + <kbd>Enter</kbd> or <kbd>Cmd</kbd> +
<kbd>Enter</kbd> at the same time, or (2) place your cursor on the line and
press the “Run” button in the upper right hand corner of the R Markdown file.
Alternatively, if you wanted to run all of the <code>R</code> code in a given code chunk,
you can click on the “Play” button in the upper right hand corner of the code
chunk (green sideways triangle).</p>
<p>If at any point you need to start over and run all of the code chunks before a
specific code chunk, you click on the “Fastforward” button in the upper right
hand corner of that code chunk (gray upside down triangle with a bar below).
This will run every code chunk that occurred <em>before</em> that code chunk, but
<em>will not</em> execute the <code>R</code> code included in that code chunk.</p>
<p>Keep your write up outside of these code chunks to avoid code errors and
failures to compile. Once you think your code and writing is done, you can use
the “Knit” button to try to compile the file. As you are learning, you may find
this challenging, so start with trying to review the sample document and knit
each time you get a line of code written so you know when you broke the file.
After you do this a couple of times, you will find that the challenge of working
with markdown files is more than matched by the simplicity of the final product
and, at least to researchers, the reproducibility and documentation of work that
this method provides.</p>
<p>Finally, when you are done with your work and attempt to exit out of
RStudio, it will ask you to save your workspace. <strong><em>DO NOT DO THIS!</em></strong> It will
just create a cluttered workspace and could even cause you to get incorrect
results. In fact, you should go into the Tools -&gt; Global Options and then make
sure that “Save workspace to .RData on exit” option on the first screen you will
see is set to <strong><em>Never</em></strong>. If you save your reports as an R Markdown (.Rmd)
file, you can re-create any results by simply re-running that code or
re-knitting the file.</p>
</div>
<div id="importing-data-into-r" class="section level3">
<h3><span class="header-section-number">1.2.6</span> Importing Data into <code>R</code></h3>
<p>When dealing with real data, we will often have information about more
than one variable. We could enter all observations by hand for each variable but
this is prone to error and onerous for all but the smallest data sets. If you
are to ever utilize the power of statistics in the evolving data-centered world,
data management has to be accomplished in a more sophisticated way. While you can
manage data sets quite effectively in <code>R</code>, it is often easiest to start with
your data set in something like Microsoft Excel or OpenOffice’s Calc. You want
to make sure that observations are in the rows and the names of variables are in
first row of the columns and that there is no “extra stuff” in the spreadsheet.
If you have missing observations, they should be represented with blank cells.
The file should be saved as a “.csv” file (stands for comma-separated values
although Excel calls it “CSV (Comma Delimited)”), which basically strips off
some of the junk that Excel adds to the necessary information in the file. Excel
will tell you that this is a bad idea, but it actually creates a more stable
archival format and one that <code>R</code> can use directly.<a href="#fn6" class="footnote-ref" id="fnref6"><sup>6</sup></a></p>
<p>In order to visualize and summarize a dataset, we first need to read the
data into <code>R</code>.  There are two ways to do this, either using
the point-and-click GUI in RStudio (click the “Import Dataset” button in the
upper right “Environment” panel as indicated in Figure <a href="chapter1.html#fig:Figure1-2">1.2</a>) or
modifying the <code>read_csv</code> function to find the file of interest.</p>
<p>Because reproducibility is a learning objective of this textbook, we will choose
option 2, modifying the <code>read_csv()</code> function to tell <code>R</code> where to import the
data from. Interestingly, there are also two ways we can get data into <code>R</code> using
the <code>read_csv()</code> function.</p>
<ol style="list-style-type: decimal">
<li>You can go to the textbook webpage in GitHub, navigate to the <em>book_data</em>
folder, and then click on the treadmill.csv file. This will bring to the file’s
location in the textbook repository. If you click on the link that says “Raw,”
you will be taken to a page that preview the raw file. Highlight the contents by
pressing <kbd>Command</kbd> + <kbd>A</kbd> (on a Mac) or <kbd>Control</kbd> +
<kbd>A</kbd> (on a PC). Then save this file to your computer by pressing
<kbd>Command</kbd> + <kbd>S</kbd> or <kbd>Control</kbd> + <kbd>S</kbd>.
Navigate to where you want for the data to be stored, and make sure the file
is saved as <em>treadmill.csv</em>!</li>
</ol>
<p>Next, in RStudio modify the code below to reflect the location of the downloaded
data:</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="chapter1.html#cb18-1"></a>treadmill &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;stat 313/week 2/data/treadmill.csv&quot;</span>)<span class="st">`</span><span class="dt"> </span></span></code></pre></div>
<p></p>
<p>Here, I’ve saved the treadmill.csv file inside a data folder, which lives inside
my week 2 folder, which lives inside my stat 313 folder. Notice, my folder
structure is organized, so that I can easily find the files I am looking for!
Organizing the files in your computer will save you a lot of headaches!</p>
<ol start="2" style="list-style-type: decimal">
<li>You can download the data directly from GitHub inside of RStudio. You would
follow the same instructions as above, but instead of downloading the data, you
would copy-and-paste the web address of the data directly into RStudio. This
would look like:</li>
</ol>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="chapter1.html#cb19-1"></a>treadmill &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;https://raw.githubusercontent.com/atheobold/stat-313/master/book_data/treadmill.csv&quot;</span>)</span></code></pre></div>
<p>Using either method, you should notice that the location of the file is enclosed
in <code>" "</code>. The <code>read_csv()</code> function takes a file path as an argument. These
quotation marks indicate to <code>R</code> that the contents between them
are a name, not an object. For example, running the following code would
produce an error, because <code>R</code> would believe that the name between the
parentheses is an object (like <code>variable1</code>), rather than the name of the location
the data are stored.</p>
<p><code>treadmill &lt;- read_csv(stat 313/week 2/data/treadmill.csv)</code>
<code>Error: unexpected numeric constant in "treadmill &lt;- read_csv(stat 313"</code></p>
<p>Using either method, <code>R</code> will store the data set as an object with the name
of the object that you put it into. Here, we named the data object <code>treadmill</code>,
the same name as the .csv file. You could use another name as well, but it is
often easiest just to keep the data set name in <code>R</code> related to the original file
name. When you run this code, you should see some text appear in the console
(lower left panel) like in Figure <a href="chapter1.html#fig:Figure1-4">1.4</a>. The text that is created
will look something like the following – if you had imported the data
directly from GitHub, it would look something like:</p>

<div class="figure" style="text-align: center"><span id="fig:Figure1-4"></span>
<img src="01/images/alt_fig%201-3.png" alt="RStudio with initial data set loaded." width="100%" />
<p class="caption">
Figure 1.4: RStudio with initial data set loaded.
</p>
</div>
</div>
<div id="inspecting-data" class="section level3">
<h3><span class="header-section-number">1.2.7</span> Inspecting Data</h3>
<p>In the spreadsheet, you will find a data with variables that contain information
on the subject number (<code>Subject</code>),
subjects’ maximum treadmill oxygen consumption (<code>TreadMillOx</code>, in ml per kg per
minute, also called maximum VO2) and maximum pulse rate (<code>TreadMillMaxPulse</code>,
in beats per minute), time to run 1.5 miles (<code>Run Time</code>, in minutes), maximum
pulse during 1.5 mile run (<code>RunPulse</code>, in beats per minute), resting pulse rate
(<code>RestPulse</code>, beats per minute), Body Weight (<code>BodyWeight</code>, in kg), and <code>Age</code>
(in years). To access the data, you have two options.</p>
<p>To verify that you read the data set in correctly, it is always good to
inspect its contents. We can view the contents of the dataset using the
following code:</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="chapter1.html#cb20-1"></a>treadmill</span></code></pre></div>
<p>This command does display the data for us, however, printing the whole dataset
in the console is not that useful. One advantage of RStudio is that it comes
with a built-in data viewer. The <em>Environment</em> tab (in the upper right pane)
lists the objects in your environment. Clicking on the name <code>treadmill</code> will
open up a <em>Data Viewer</em> tab next to your R Markdown file, which provides an
alternative display of the data set. This display should feel similar to viewing
data in Excel, where you are able to scroll through the dataset to inspect it.
However, unlike Excel, you <strong>will not</strong> be able to edit the data in this tab.
Once you are done viewing the data, You can close this tab by clicking on the
<code>x</code> in the upper left hand corner.</p>
<p>When inspecting the data, you should see eight columns of numbers and 31 rows.
Each row represents a different subject in the study. The first entry in each
row is the row number (an index we can use to access the data from individual
years if we want), the second is the subject number, and the rest of the columns
are the variables for which data was collected for every subject. You can use
the scrollbar on the right side of the console window to examine the complete
data set.</p>
<p>Note that the row numbers in the first column are not part of the <code>treadmill</code>
data. <code>R</code> adds these row numbers as part of its printout to help you make visual
comparisons. You can think of them as the index that you see on the left side of
a spreadsheet. In fact, the comparison of the data to a spreadsheet will
generally be helpful. <code>R</code> has stored the <code>treadmill</code> data in an object similar
to a spreadsheet or a table, which <code>R</code> calls a <em>data frame</em>.</p>
<p>You can see the dimensions of this data frame as well as the names of the
variables and the first few observations by inserting the name of the dataset
into the <code>glimpse()</code> function, as seen below:</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="chapter1.html#cb21-1"></a><span class="kw">glimpse</span>(treadmill)</span></code></pre></div>
<p>Although we previously said that it is best practice to type all of your <code>R</code>
code into the code chunk, it is better practice to type this command into your
console. Generally, you should type all of the code that is necessary for your
solution into the code chunk. Because this command is used to explore the data,
it is not necessary for your solution code and <strong>should not</strong> be included in
your R Markdown file.</p>
<p>This command should output the following:</p>
<pre><code>## Rows: 31
## Columns: 8
## $ Subject           &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, …
## $ TreadMillOx       &lt;dbl&gt; 60.05, 59.57, 54.62, 54.30, 51.85, 50.55, 50.54, 50…
## $ TreadMillMaxPulse &lt;dbl&gt; 186, 172, 155, 168, 170, 155, 168, 168, 180, 185, 1…
## $ RunTime           &lt;dbl&gt; 8.63, 8.17, 8.92, 8.65, 10.33, 9.93, 10.13, 10.08, …
## $ RunPulse          &lt;dbl&gt; 170, 166, 146, 156, 166, 148, 168, 168, 178, 180, 1…
## $ RestPulse         &lt;dbl&gt; 48, 40, 48, 45, 50, 49, 45, 67, 55, 44, 64, 56, 52,…
## $ BodyWeight        &lt;dbl&gt; 81.87, 68.15, 70.87, 85.84, 83.12, 59.08, 73.03, 73…
## $ Age               &lt;dbl&gt; 38, 42, 50, 44, 54, 57, 44, 49, 38, 49, 43, 49, 48,…</code></pre>
<p></p>
<p>At this point, you might notice that many of the commands in <code>R</code> look a lot like
functions from math class; that is, invoking <code>R</code> commands means supplying a
function with some number of inputs (what are called arguments) which the
function uses to produce an output. The <code>glimpse()</code> command, for example, took a
single argument, the name of a data frame and produced a display of the dataset
as an output.</p>
</div>
</div>
<div id="section1-3" class="section level2">
<h2><span class="header-section-number">1.3</span> Introduction to Data Summarization</h2>
<p>The <code>treadmill</code> object is what <code>R</code> calls a <strong><em>tibble</em></strong><a href="#fn7" class="footnote-ref" id="fnref7"><sup>7</sup></a> and contains columns
corresponding to each variable in the spreadsheet. Every function in <code>R</code> will
involve specifying the variable(s) of interest and how you want to use them.
To access a particular variable (column) in a tibble, you can use a <code>$</code> between
the name of the tibble and the name of the variable of interest. Generically,
this looks something like: <code>tibblename$variablename</code>. You can think of this as
<em>tibblename’s variablename</em> where the <em>’s</em> is replaced by the dollar sign (<code>$</code>).
To access the <code>RunTime</code> variable here it would be <code>treadmill$RunTime</code>.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="chapter1.html#cb23-1"></a>treadmill<span class="op">$</span>RunTime</span></code></pre></div>
<pre><code>##  [1]  8.63  8.17  8.92  8.65 10.33  9.93 10.13 10.08  9.22  8.95 10.85  9.40
## [13] 11.50 10.50 10.60 10.25 10.00 11.17 10.47 11.95  9.63 10.07 11.08 11.63
## [25] 11.12 11.37 10.95 13.08 12.63 12.88 14.03</code></pre>
<p>When we looked at the complete data frame, we saw 31 rows, one on each line of
the display. These data have been extracted from the data frame, so they are no
longer structured in a table with other variables. Instead, these data are
displayed one right after another. Objects that print out in this way are called
<em>vectors</em>; similar to the vectors you have seen in mathematics courses, vectors
represent a list of numbers. <code>R</code> has added numbers displayed in [brackets] along
the left side of the printout to indicate each entry’s location within the
vector. For example, 8.63 follows <code>[1]</code>, indicating that <code>8.63</code> is the first
entry in the vector. If <code>[43]</code> was displayed at the beginning of a line, that
indicate that the first number displayed on that line would correspond to the
43<sup>rd</sup> entry in that vector.</p>
<p>Just as in the previous section, we can generate summary statistics for
a particular variable using functions like <code>mean()</code> and <code>sd()</code>:

</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="chapter1.html#cb25-1"></a><span class="kw">mean</span>(treadmill<span class="op">$</span>RunTime)</span></code></pre></div>
<pre><code>## [1] 10.58613</code></pre>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="chapter1.html#cb27-1"></a><span class="kw">sd</span>(treadmill<span class="op">$</span>RunTime)</span></code></pre></div>
<pre><code>## [1] 1.387414</code></pre>
<p>And now we know that the average running time for 1.5 miles for the subjects
in the study was 10.586129 minutes with a standard
deviation of 1.3874141 minutes. But you should remember that
the mean and SD are only appropriate summaries if the distribution is roughly
<strong><em>symmetric</em></strong> (both sides of the distribution are approximately the same shape
and length).</p>
<!-- (Note: answers to all Guided Practice exercises are provided in footnotes!) -->
<div class="guidedpractice">
<p>But how can we determine if the distribution of a variable is symmetric?<a href="#fn8" class="footnote-ref" id="fnref8"><sup>8</sup></a></p>
</div>
<p>The <strong>dplyr</strong> package (included in the tidyverse) provides a useful function
called <code>summarize()</code> that allows
for us to calculate many different summary statistics all at the same time. A
<strong><em>five number summary</em></strong> is a common calculation people use to assess the
distribution of a variable, where the summaries are 
the minimum (<code>min</code>), the first quartile (<code>Q1</code>, the 25<sup>th</sup> percentile),
the <code>median</code> (50<sup>th</sup> percentile), the third quartile (<code>Q3</code>, the 75<sup>th</sup>
percentile), and the maximum (<code>max</code>).
</p>
<p>Let’s use the <code>summarize()</code> function to calculate a five number summary of the
running times, including the mean:</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="chapter1.html#cb29-1"></a><span class="kw">summarize</span>(treadmill, </span>
<span id="cb29-2"><a href="chapter1.html#cb29-2"></a>          <span class="dt">min =</span> <span class="kw">min</span>(RunTime), </span>
<span id="cb29-3"><a href="chapter1.html#cb29-3"></a>          <span class="dt">Q1 =</span> <span class="kw">quantile</span>(RunTime, <span class="dt">probs =</span> <span class="fl">0.25</span>),</span>
<span id="cb29-4"><a href="chapter1.html#cb29-4"></a>          <span class="dt">mean =</span> <span class="kw">mean</span>(RunTime), </span>
<span id="cb29-5"><a href="chapter1.html#cb29-5"></a>          <span class="dt">median =</span> <span class="kw">median</span>(RunTime), </span>
<span id="cb29-6"><a href="chapter1.html#cb29-6"></a>          <span class="dt">Q3 =</span> <span class="kw">quantile</span>(RunTime, <span class="dt">probs =</span> <span class="fl">0.75</span>), </span>
<span id="cb29-7"><a href="chapter1.html#cb29-7"></a>          <span class="dt">max =</span> <span class="kw">max</span>(RunTime), </span>
<span id="cb29-8"><a href="chapter1.html#cb29-8"></a>)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 6
##     min    Q1  mean median    Q3   max
##   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1  8.17  9.78  10.6   10.5  11.3  14.0</code></pre>
<p>This code may look overwhelming, so let’s break it down! The first argument
(input) into the <code>summarize()</code> function is the name of the dataset you would
like to summarize. Next, you tell the function all of the summaries you would
like, giving names to each summary. Here, we give simple names to the summaries,
e.g. <code>min</code> or <code>median</code> or <code>Q3</code>, which are indicated on the left-hand side of the
<code>=</code> sign. On the right-hand side of the <code>=</code> sign is the calculation you want
<code>R</code> to do for you. <code>R</code> has built-in functions for calculating the <code>min()</code>,
<code>max()</code>, <code>median()</code>, and percentiles of a distribution.</p>
<p>The <code>quantile()</code> function may look a little confusing, so let’s look at what is
going on. There are two arguments to <code>quantile()</code>, the a numeric vector, and
a percentage. The percentage tells the function what percent of the data you
want to be below. For example, in Figure <a href="chapter1.html#fig:Figure1-5">1.5</a> we can see that
the first quantile corresponds to the number where approximately 25% of the data
is below that number and 75% is above that number. This should make a bit more
sense if you think about the median being the center of the distribution, where
50% of the data is below the median and 50% is above.</p>

<div class="figure" style="text-align: center"><span id="fig:Figure1-5"></span>
<img src="01/images/quantile.jpg" alt="Quantiles of a distribution." width="100%" />
<p class="caption">
Figure 1.5: Quantiles of a distribution.
</p>
</div>
<p>Alternatively, we could have used the following code to obtain the same
five number summary:</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="chapter1.html#cb31-1"></a>treadmill <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb31-2"><a href="chapter1.html#cb31-2"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">min =</span> <span class="kw">min</span>(RunTime), </span>
<span id="cb31-3"><a href="chapter1.html#cb31-3"></a>            <span class="dt">Q1 =</span> <span class="kw">quantile</span>(RunTime, <span class="dt">probs =</span> <span class="fl">0.25</span>),</span>
<span id="cb31-4"><a href="chapter1.html#cb31-4"></a>            <span class="dt">mean =</span> <span class="kw">mean</span>(RunTime), </span>
<span id="cb31-5"><a href="chapter1.html#cb31-5"></a>            <span class="dt">median =</span> <span class="kw">median</span>(RunTime), </span>
<span id="cb31-6"><a href="chapter1.html#cb31-6"></a>            <span class="dt">Q3 =</span> <span class="kw">quantile</span>(RunTime, <span class="dt">probs =</span> <span class="fl">0.75</span>), </span>
<span id="cb31-7"><a href="chapter1.html#cb31-7"></a>            <span class="dt">max =</span> <span class="kw">max</span>(RunTime), </span>
<span id="cb31-8"><a href="chapter1.html#cb31-8"></a>)</span></code></pre></div>
<p>The only difference between the previous code and this code is the location of
the <code>treadmill</code> data. Previously, we told the <code>summarize()</code> function to use
the <code>treadmill</code> data by inserting the data as the first argument into the
function. Here, we instead “pipe” the <code>treadmill</code> data into the <code>summarize()</code>
function using what is called the pipe operator (<code>%&gt;%</code>).</p>
<p>You might be wondering what we mean by <em>“pipe it into the <code>summarize()</code> function”</em>?</p>
<div id="the-pipe-operator" class="section level3">
<h3><span class="header-section-number">1.3.1</span> The Pipe Operator</h3>
<p><img src="01/images/pipe-operator.png" width="50%" style="display: block; margin: auto;" /></p>
<p>The <strong>pipe operator</strong>, which <strong>is percent greater than percent</strong>, tells <code>R</code> to
pass the object that comes before it into the first argument of the function
that comes after it. Mathematically, <strong>x pipe f(y)</strong> becomes <em>f(x, y)</em>, since x
is piped into the first argument of the function f( ).</p>
<p><img src="01/images/pipe-operator2.png" width="50%" style="display: block; margin: auto;" /></p>
<p>You may think that it seems kind of silly to use the pipe rather than simply
typing the name of the data into the <code>summarize()</code> function, but as we progress
through the textbook, acquiring additional data wrangling skills, you will see
that the piping operator will allow us to sequentially link together data
wrangling operations. This can save us a great deal of headache later on, as the
format of operations that use the pipe are far simpler to read! We’ll start with
short pipes and throughout the tutorial build up to longer pipes that perform
multiple operations.</p>
</div>
</div>
<div id="section1-4" class="section level2">
<h2><span class="header-section-number">1.4</span> Introduction to Data Visualization in <code>R</code></h2>
<p>We are starting to get somewhere with understanding that the runners
were somewhat fit with the worst runner covering 1.5 miles in 14 minutes
(the equivalent of a 9.3 minute mile) and the best running at a 5.4 minute mile
pace. The limited variation in the results suggests that the sample was obtained
from a restricted group with somewhat common characteristics. When you explore
the ages and weights of the subjects in the Practice Problems in Section
<a href="chapter1.html#section1-7">1.7</a>, you will get even more information about how similar all the
subjects in this study were. Researchers often publish numerical summaries of
this sort of demographic information to help readers understand the subjects
that they studied and that their results might apply to.</p>
<p>A graphical display of the variable is a simpler method to help us to
assess the shape of its distribution – including considering the potential for
the presence of a <strong><em>skew</em></strong> (whether the right or left tail of the distribution
is noticeably more spread out, with left skew meaning that the left tail
is more spread out than the right tail)  and <strong><em>outliers</em></strong>
 (unusual observations). A <strong><em>histogram</em></strong>  is a
good place to start. Histograms display connected bars with counts of
observations defining the height of bars based on a set of bins of values of the
quantitative variable.</p>
<p><code>R</code> has some powerful functions for making graphics. We chose ggplot2 because
this package makes modern looking hassle-free plots that take care of fiddly
details like drawing legends. Additionally, once you learn how to make simple
bivariate plots, with ggplot2 it is easy to extend your code to create a
visualization that displays the relationship between many variables at once
without having to learn too much more syntax.</p>
<div id="histogram" class="section level3">
<h3><span class="header-section-number">1.4.1</span> Histogram</h3>
<p>We can create a simple plot of the distribution of the running times with the
following code:</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="chapter1.html#cb32-1"></a><span class="kw">ggplot</span>(<span class="dt">data =</span> treadmill, <span class="kw">aes</span>(<span class="dt">x =</span> RunTime)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb32-2"><a href="chapter1.html#cb32-2"></a><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">10</span>)</span></code></pre></div>
<p><img src="01-preface_files/figure-html/unnamed-chunk-25-1.png" width="480" /></p>
<p>In this code, we use the <code>ggplot()</code> function to build a plot. If you run this
code chunk, a plot will appear below the code chunk. The R Markdown document
displays the plot below the code that was used to generate it, to give you an
idea of what the plot would look like in a final report.</p>
<p>The command above also looks like a mathematical function.
This time, however, the function requires multiple inputs (arguments), which are
separated by commas.</p>
<p>With <code>ggplot()</code>:</p>
<ul>
<li>The first argument is always the name of the dataset you wish to use for
plotting.</li>
<li>Next, you provide the variables from the dataset to be assigned to different
<code>aes</code>thetic elements of the plot, such as the x and the y axes.</li>
</ul>
<p>These commands will build a blank plot, with the variables you assigned to the x
and y axes, as seen below.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="chapter1.html#cb33-1"></a><span class="kw">ggplot</span>(<span class="dt">data =</span> treadmill, <span class="kw">aes</span>(<span class="dt">x =</span> RunTime))</span></code></pre></div>
<p><img src="01-preface_files/figure-html/unnamed-chunk-26-1.png" width="480" /></p>
<p>Next, you need to tell <code>ggplot()</code> what type of visualization you
would like to add to the blank template. You add another layer to the <code>ggplot()</code>
by:</p>
<ul>
<li>adding a <code>+</code> at the end of the line, to indicate that you are adding a layer</li>
<li>then specify the <code>geom</code>etric object to be used to create the plot.</li>
</ul>
<p>Since we want to create a histogram, we use <code>geom_histogram()</code>. This tells
<code>ggplot()</code> to take the data values and bin them up, so that the height of each
bin reflects the number of observations included in that bin. We then specify
the number of bins we want <code>geom_histogram()</code> to make, by providing a number
to the <code>bins</code> argument.</p>
<p>Based on this histogram, it does not
appear that there any outliers in the responses since there are no bars that are
separated from the other observations. However, the distribution does not look
symmetric and there might be a skew to the distribution. Specifically, it
appears to be <strong><em>skewed right</em></strong> (the right tail is longer than the left).
Histograms can sometimes mask features of the data set by binning observations,
making it difficult to find the percentiles accurately from the plot.
Alternative visualizations for these data would be a boxplot or a density plot,
which we will explore next.</p>
</div>
<div id="boxplot" class="section level3">
<h3><span class="header-section-number">1.4.2</span> Boxplot</h3>
<p>When assessing outliers and skew, the <strong><em>boxplot</em></strong>
(or <em>Box and Whiskers</em> plot) can also be helpful to describe the
shape of the distribution as it displays the 5-number summary and will also
indicate observations that are “far” above the middle of the observations.
</p>
<p>As you may have expected, to create a boxplot in ggplot you change the
geometric representation of your data, in the <code>geom</code> function. Here, we will
use the <code>geom_boxplot()</code> to create a boxplot of the running times. The
<code>geom_boxplot()</code> function uses the standard rule to indicate an observation as a
<strong><em>potential outlier</em></strong> if it falls more than 1.5 times the <strong><em>IQR</em></strong>
(Inter-Quartile Range, calculated as Q3 – Q1) below Q1 or above Q3.
</p>
<p>The potential outliers are plotted with circles and the <em>Whiskers</em> (lines that
extend from Q1 and Q3 typically to the minimum and maximum) are shortened to
only go as far as observations that are within <span class="math inline">\(1.5 \times \text{IQR}\)</span> of the
upper and lower quartiles. The <em>box</em> part of the boxplot is a box that goes from
Q1 to Q3 and the median is displayed as a line somewhere inside the box.<a href="#fn9" class="footnote-ref" id="fnref9"><sup>9</sup></a></p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="chapter1.html#cb34-1"></a><span class="kw">ggplot</span>(<span class="dt">data =</span> treadmill, <span class="kw">aes</span>(<span class="dt">y =</span> RunTime)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb34-2"><a href="chapter1.html#cb34-2"></a><span class="st">  </span><span class="kw">geom_boxplot</span>()</span></code></pre></div>
<p><img src="01-preface_files/figure-html/unnamed-chunk-27-1.png" width="480" /></p>
<p>You’ll notice there is one additional change in the code above – the
running times are now the y variable instead of the x variable. This is because
it is more “standard” for a boxplot to appear vertically rather than
horizontally. Thus, plotting <code>RunTime</code> as the y variable, creates a vertical
boxplot.</p>
<!-- Second, there are empty quotations next to the x variable. This is  -->
<!-- because `ggplot()` expects for us to be creating multiple boxplots  -->
<!-- (side-by-side boxplots) when we use `geom_boxplot()`. To create a boxplot of  -->
<!-- only one group, you need to insert an empty variable (`" "`) as the x variable.  -->
<p>Looking at the boxplot, one observation, the maximum, was flagged as an
“outlier” and plotted as a point. In the summary statistics we calculated
before, Q1 was 9.78 and Q3 was
11.27, providing an IQR of:</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="chapter1.html#cb35-1"></a>treadmill <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb35-2"><a href="chapter1.html#cb35-2"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">IQR =</span> <span class="kw">quantile</span>(RunTime, <span class="dt">probs =</span> <span class="fl">0.75</span>) <span class="op">-</span><span class="st"> </span></span>
<span id="cb35-3"><a href="chapter1.html#cb35-3"></a><span class="st">              </span><span class="kw">quantile</span>(RunTime, <span class="dt">probs =</span> <span class="fl">0.25</span>)</span>
<span id="cb35-4"><a href="chapter1.html#cb35-4"></a>            )</span></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##     IQR
##   &lt;dbl&gt;
## 1  1.49</code></pre>
<p>Based on this result the maximum (14.03) was flagged as a
potential outlier, because it was larger than than Q3 <span class="math inline">\(+1.5*\)</span>IQR, which was
13.505.</p>
<p>The boxplot also shows a slight indication of a right skew (skew towards
larger values) with the distance from the minimum to the median being smaller
than the distance from the median to the maximum. Additionally, the distance
from Q1 to the median is smaller than the distance from the median to Q3. It is
modest skew, but worth noting.</p>
<p>While the default boxplot is okay, it fails to provide good graphical
labels, especially on the y-axis. Additionally, there is no title on the plot.
The following code provides some enhancements to the plot by using the <code>labs()</code>
function to add labels to the plot. When we add text to plots, it must be
contained within quotes and be assigned into the options <code>y</code> (for y-axis),
<code>x</code> (for x-axis), or <code>title</code> (for the title) here to put it into those
locations.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="chapter1.html#cb37-1"></a><span class="kw">ggplot</span>(<span class="dt">data =</span> treadmill, <span class="kw">aes</span>(<span class="dt">y =</span> RunTime)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb37-2"><a href="chapter1.html#cb37-2"></a><span class="st">  </span><span class="kw">geom_boxplot</span>() <span class="op">+</span><span class="st"> </span></span>
<span id="cb37-3"><a href="chapter1.html#cb37-3"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">y =</span> <span class="st">&quot;1.5 Mile Run Time (minutes)&quot;</span>,</span>
<span id="cb37-4"><a href="chapter1.html#cb37-4"></a>       <span class="dt">title =</span> <span class="st">&quot;Boxplot of the Run Times of 31 participants&quot;</span>)</span></code></pre></div>
<p><img src="01-preface_files/figure-html/unnamed-chunk-29-1.png" width="480" /></p>
<p>Unfortunately, boxplots can be misleading. They are not affected by data’s
distribution, which allows for the data to “morph” but maintain their stat
summaries (medians and ranges), their box plots stay the same. One of the ways
this “morphing” becomes extremely problematic, is if a distribution looks okay
on a boxplot, but actually has multiple peaks (called modes). Density plots
allow for us to detect these small changes in the distribution of a variable
far more easily.</p>
</div>
<div id="density-plot" class="section level3">
<h3><span class="header-section-number">1.4.3</span> Density Plot</h3>
<p>To create a density plot instead of a histogram or boxplot, (as expected) you
would use <code>geom_density()</code>. This would tell <code>ggplot()</code> to
draw a continuous line around the outside of the histogram, where the height of
the density curve reflects the number of observations at that run time. Another,
potentially less noticeable difference, is that a density plot has different
values on the y-axis. A histogram has counts on the y-axis, representing the
number of observations in each bin. A density plot, however, has density on the
y-axis, with values between 0 and 1. If you remember from your introductory
statistics course, the total area under a a density plot adds up to 100%, so
the values on the side represent the percentage of the data that
took on values in that data range. For example, it appears that nearly 30% of
the runners in this study had running times around 11 minutes for the 1.5 miles.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="chapter1.html#cb38-1"></a><span class="kw">ggplot</span>(<span class="dt">data =</span> treadmill, <span class="kw">aes</span>(<span class="dt">x =</span> RunTime)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb38-2"><a href="chapter1.html#cb38-2"></a><span class="st">  </span><span class="kw">geom_density</span>()</span></code></pre></div>
<p><img src="01-preface_files/figure-html/unnamed-chunk-30-1.png" width="480" /></p>
<div class="protip">
<p>Many people would prefer for their density plot to be filled in (shaded) below
the density line. To do this you need to add a color to the <code>fill</code> argument,
inside the <code>geom_density()</code> function. This tells <code>ggplot()</code> that you want for
your density curvy to be filled with whatever color you tell it. Here, I’ve
selected blue, although tomato is another favorite of mine.</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="chapter1.html#cb39-1"></a><span class="kw">ggplot</span>(<span class="dt">data =</span> treadmill, <span class="kw">aes</span>(<span class="dt">x =</span> RunTime)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb39-2"><a href="chapter1.html#cb39-2"></a><span class="st">  </span><span class="kw">geom_density</span>(<span class="dt">fill =</span> <span class="st">&quot;blue&quot;</span>)</span></code></pre></div>
<p><img src="01-preface_files/figure-html/unnamed-chunk-31-1.png" width="480" /></p>
</div>
</div>
<div id="recap" class="section level3">
<h3><span class="header-section-number">1.4.4</span> Recap</h3>
<p>You might wonder how you are supposed to know the syntax for the <code>ggplot()</code>
function. Thankfully, <code>R</code> documents all of its functions extensively. To learn
what a function does and how to use it (e.g. the function’s arguments), just
type in a question mark followed by the name of the function that you’re
interested in into the console. Type the following in your console:</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="chapter1.html#cb40-1"></a>?ggplot</span></code></pre></div>
<p>Notice that the help file comes to the forefront, replacing the plot in the
lower right panel. You can toggle between the tabs by clicking on their names.</p>
<p>Throughout the book, we will often use extra options to make figures that
are easier for you to understand. There are often ways to create the same plots
using base <code>R</code> functions, but we feel that ggplot2 makes it simple for you to
create complex plots from data stored in a data frame. Additionally, ggplot2
provides a programmatic interface for specifying what variables to plot, how
they are displayed, and general visual properties. Therefore, we only need
minimal changes if the underlying data change or if we decide to change from a
bar plot to a scatterplot. This helps in creating high quality plots with
minimal amounts of adjustments and tweaking.</p>
</div>
</div>
<div id="section1-5" class="section level2">
<h2><span class="header-section-number">1.5</span> Chapter Summary</h2>
<p>This chapter covered getting R and RStudio downloaded and some basics of working
with <code>R</code> via RStudio. After reading this chapter, you should have an
understanding of reading a data set into <code>R</code>, making simple data summaries, and
creating visualizations for a single quantitative variable, all done in RStudio.
If you are struggling with this, you should seek additional help with these
technical issues so that you are ready for more complicated statistical methods
that are going to be encountered in the following chapters. The way everyone
learns <code>R</code> is by starting with some example code that does (most) of what you
want to accomplish and then you modifying it to meet your needs. If you can
complete the Practice Problems that follow, you are well on your way to learning
to use <code>R</code>.</p>
<p>The statistical methods in this chapter were minimal and all should have
been review. They involved a quick reminder of summarizing the center, spread,
and shape of distributions using numerical summaries of the mean and standard
deviation and/or a five number summary (min, Q1, median, Q3, max). We also
reviewed histograms, boxplots, and density plots as visualizations for the
distribution for a quantitative variable, and the benefits/deficiencies of each
type of plot. We connected these visualizations to the ideas of symmetry and
skew. But the main focus of the chapter was on introducing you to using <code>R</code> via
RStudio, so you are prepared for future statistical investigations!</p>
<div style="page-break-after: always;"></div>
</div>
<div id="section1-6" class="section level2">
<h2><span class="header-section-number">1.6</span> Summary of Important R code</h2>
<p>To help you learn and use <code>R</code>, there is a section highlighting the most
important <code>R</code> code used near the end of each chapter. The bold text will never
change but the lighter and/or ALL CAPS text (red in the online or digital
version) will need to be customized to your particular application. The
sub-bullet for each function will discuss the use of the function and pertinent
options or packages required. You can use this as a guide to finding the
function names and some hints about options that will help you to get the code
to work. You can also revisit the worked examples using each of the functions.</p>
<ul>
<li><p><font color='red'>OBEJECT_NAME</font> <code>&lt;-</code> <strong>read_csv(</strong><font color='red'>“path_to_csv_file/FILE_NAME.csv”</font><strong>)</strong></p>
<ul>
<li><p>Requires the <code>tidyverse</code> package to be loaded (<code>library(tidyverse)</code> after
installing the package).</p></li>
<li><p>Imports a data file saved in the CSV format, and assigns it to
<font color='red'>OBJECT_NAME</font>.</p></li>
</ul></li>
<li><p><strong><code>&lt;-</code></strong></p>
<ul>
<li><p>Called the “assignment operator.”</p></li>
<li><p>Assigns the value on the right-hand side into the name of the object
on the left-hand side (e.g. <code>variable1 &lt;- c(1, 2, 3, 4)</code>).</p></li>
</ul></li>
<li><p><font color='red'>DATASET_NAME</font><strong>$</strong><font color='red'>VARIABLE_NAME</font></p>
<ul>
<li>To access a particular variable in a tibble called
<font color='red'>DATASET_NAME</font>, use a $ and then the
<font color='red'>VARIABLE_NAME</font>.</li>
</ul></li>
<li><p><strong>glimpse(</strong><font color='red'>DATASET_NAME</font><strong>)</strong></p>
<ul>
<li>Provides a preview of your dataset, listing the name and data type of
every column, and providing the first few rows (entries) of each variable.
</li>
</ul></li>
<li><p><strong>mean(</strong><font color='red'>VARIABLE_NAME</font><strong>)</strong></p>
<ul>
<li>Calculates the mean of the observations in a variable, where the variable
is required to be numerical.
</li>
</ul></li>
<li><p><strong>sd(</strong><font color='red'>VARIABLE_NAME</font><strong>)</strong></p>
<ul>
<li>Calculates the standard deviation of the observations in a variable,
where the variable is required to be numerical.
</li>
</ul></li>
<li><p><strong>min(</strong><font color='red'>VARIABLE_NAME</font><strong>)</strong></p>
<ul>
<li>Calculates the minimum of the observations in a variable, where the
variable is required to be numerical.
</li>
</ul></li>
<li><p><strong>max(</strong><font color='red'>VARIABLE_NAME</font><strong>)</strong></p>
<ul>
<li>Calculates the maximum of the observations in a variable, where the
variable is required to be numerical.
</li>
</ul></li>
<li><p><strong>quantile(</strong><font color='red'>VARIABLE_NAME</font>,
<strong>probs =</strong> <font color='red'>PERCENT_OF_DATA_BELOW</font><strong>)</strong></p>
<ul>
<li>Calculates the quantile of a numerical variable, where the quantile is
based on the of input to the <code>probs</code> argument. <code>probs = 0.5</code> calculates the
median, <code>probs = 0.25</code> calculates the first quartile (Q1), and
<code>probs = 0.75</code> calculates the third quartile (Q3).
</li>
</ul></li>
<li><p><strong>summarize(</strong><font color='red'>DATASET_NAME</font>,
<font color='red'>DATA_SUMMARIES</font><strong>)</strong></p>
<ul>
<li><p>Requires the <code>tidyvere</code> package to be loaded (<code>library(tidyverse)</code> after
installing the package).</p></li>
<li><p>Allows for you to create summaries of variables in a dataset, where
each summary has an assigned name (e.g. <code>mean =</code>) and a method to calculate
the summary (e.g. <code>mean(VARIABLE_NAME)</code>). </p></li>
</ul></li>
<li><p><strong><code>%&gt;%</code></strong></p>
<ul>
<li><p>Called the “pipe operator”.</p></li>
<li><p>Pipes data from the previous line (above) into the next function (i.e. 
the previous data becomes the first argument in the subsequent function).</p></li>
<li><p>Allows for you to link together data wrangling processes, promoting the
readability of each step.
\index{\texttt{%&gt;%}|textbf}</p></li>
</ul></li>
<li><p><strong>ggplot(data =</strong> <font color='red'>DATASET_NAME</font>,
<strong>aes(x =</strong> <font color='red'>VARIABLE</font>,
<strong>y =</strong> <font color='red'>VARIABLE_NAME</font><strong>))</strong></p>
<ul>
<li><p>The function we use to create different types of plots.</p></li>
<li><p>The first argument is the dataframe containing the data we wish to plot.</p></li>
<li><p>In the aesthetics argument (<code>aes()</code>), we map variables from the dataframe
to certain components of the plot (e.g. the variables that should go on
the x- and y-axis).
</p></li>
</ul></li>
<li><p><strong>geom_histogram( )</strong></p>
<ul>
<li>Specifies what geometric shapes should be used to represent the
observations. In this case, a histogram of the observations is created,
where the observations are binned into ranges of values and then frequencies
of observations are plotted on the y-axis.
</li>
</ul></li>
<li><p><strong>geom_boxplot( )</strong></p>
<ul>
<li>Specifies observations should be aggregated (summarized) into a boxplot,
where the min, Q1, median, Q3, and maximum are plotted as the box and
whiskers, and “outliers” are plotted as points. Note: the min and max may
not be included in the whiskers, if they are deemed to be “outliers” based
on the <span class="math inline">\(1.5 \times \text{IQR}\)</span> rule.
</li>
</ul></li>
<li><p><strong>geom_density(fill =</strong> “<font color='red'>COLOR_OF_CHOICE</font>”<strong>)</strong></p>
<ul>
<li><p>Specifies observations should be plotted as a density curve, where
the probability density is plotted on the y-axis (so the density curve
has a total area of one).</p></li>
<li><p>By default this creates a density curve without shading. By specifying a
color in the <code>fill</code> argument, the density curve is shaded, making it easier
to detect changes in the distribution.
</p></li>
</ul></li>
<li><p><strong>+</strong></p>
<ul>
<li><p>An important aspect creating a <code>ggplot()</code> is to note that the
<code>geom_XXX()</code> function is separated from the <code>ggplot()</code> function with a plus,
<code>+</code>.</p></li>
<li><p>ggplot2 plots are constructed in series of layers, where the plus sign
separates these layers.</p></li>
<li><p>Generally, the <code>+</code> sign can be thought of as the end of a line, so you
should always hit enter/return after it. While it is not mandatory to move
to the next line for each layer, doing so makes the code a lot easier to
organize and read.</p></li>
</ul></li>
</ul>
<div style="page-break-after: always;"></div>
</div>
<div id="section1-7" class="section level2">
<h2><span class="header-section-number">1.7</span> Practice Problems</h2>
<p>In each chapter, the last section contains some questions for you to complete
to make sure you understood the material. You can download the code to answer
questions 1.1 to 1.5 below at <a href="https://raw.githubusercontent.com/atheobold/stat-313/master/Week%202/Reading/Chapter%20One%20Practice%20Problem%20Solutions/Chapter%20One%3A%20Introduction%20to%20R%20and%20RStudio.Rmd">Course GitHub Page</a>.
But to practice learning <code>R</code>, it would be most useful for you to try
to accomplish the requested tasks yourself and then only refer to the provided
<code>R</code> code if/when you struggle. These questions provide a great venue to check
your learning, often to see the methods applied to another data set, and for
something to discuss in study groups, with your instructor, and at the campus
tutoring center.</p>
<p>1.1. Read in the treadmill data set discussed previously and use the
<code>summarize()</code> function to find the mean and standard deviation of the Ages
(<code>Age</code> variable) and Body Weights (<code>BodyWeight</code> variable). In studies
involving human subjects, it is common to report a
summary of characteristics of the subjects. Why does this matter? Think about
how your interpretation of any study of the fitness of subjects would change if
the mean age (same spread) had been 20 years older or 35 years younger.</p>
<p>1.2. How does knowing about the distribution of results for <code>Age</code> and
<code>BodyWeight</code> variables help you understand the results for the run times
discussed previously?</p>
<p>1.3. The mean and standard deviation are useful as summary statistics <strong>if</strong>
the distribution is relatively symmetric. Make a density plot of <code>Age</code> responses
and discuss the shape of the distribution. Is it skewed right, skewed left,
approximately symmetric? Are there outliers? Approximately what range of
ages does this study pertain to?</p>
<p>1.4. The weight responses are in kilograms and you might prefer to see them in
pounds. We can use the <code>mutate()</code> function to create a new variable from an
existing variable. In the example below, we use the <code>mutate()</code> function to add a
new variable to the dataset, that is the difference between runner’s running
pulse and resting pulse. We add the variable to the original dataframe, by
assigning the new dataframe into the name of the old dataframe
(<code>treadmill &lt;-</code>).</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="chapter1.html#cb41-1"></a>treadmill &lt;-<span class="st"> </span>treadmill <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb41-2"><a href="chapter1.html#cb41-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">diff_pulse =</span> RunPulse <span class="op">-</span><span class="st"> </span>RestPulse)</span></code></pre></div>
<p>Use the above code example to create a new column named <code>BodyWeight_lb</code> in the
treadmill dataframe. The conversion from kg to lb is <span class="math inline">\(\text{lbs} = 2.205 \times \text{kgs}\)</span>.</p>
<p>After you create the new variable, use <code>summarize()</code> to find the mean and
standard deviation of the new variable (<code>BodyWeight_lb</code>).</p>
<p>1.5. Make boxplots and density plots of the original <code>BodyWeight</code> and new
<code>BodyWeight_lb</code> variables. Discuss aspects of the distributions that changed and
those that remained the same with the transformation from kilograms to pounds.
What does this tell you about changing the units of a variable in terms of its
distribution?</p>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-Gandrud2015">
<p>Gandrud, Christopher. 2015. <em>Reproducible Research with R and R Studio, Second Edition</em>. Chapman Hall, CRC.</p>
</div>
<div id="ref-R-base">
<p>R Core Team. 2020. <em>R: A Language and Environment for Statistical Computing</em>. Vienna, Austria: R Foundation for Statistical Computing. <a href="https://www.R-project.org/">https://www.R-project.org/</a>.</p>
</div>
<div id="ref-RStudio">
<p>RStudio Team. 2018. <em>RStudio: Integrated Development Environment for R</em>. Boston, MA: RStudio, Inc. <a href="http://www.rstudio.com/">http://www.rstudio.com/</a>.</p>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="1">
<li id="fn1"><p>A <strong><em>placebo</em></strong> is a treatment level designed
to mimic the potentially efficacious level(s) but that can have no actual
effect. The <strong><em>placebo effect</em></strong> is the effect that thinking that an effective
treatment was received has on subjects. There are other related issues in
performing experiments like the <strong><em>Hawthorne</em></strong> or <strong><em>observer effect</em></strong> where
subjects modify behavior because they are being observed.<a href="chapter1.html#fnref1" class="footnote-back">↩︎</a></p></li>
<li id="fn2"><p>We will reserve the term “effect” for situations where we
could potentially infer causal impacts on the response of the explanatory
variable which occurs in situations where the levels of the explanatory variable
are randomly assigned to the subjects.<a href="chapter1.html#fnref2" class="footnote-back">↩︎</a></p></li>
<li id="fn3"><p>There is a cloud version of R Studio available at
<a href="https://rstudio.cloud/" class="uri">https://rstudio.cloud/</a> that is free for limited usage. We recommend following
the steps to be able to work locally but try this option if you have issues with
the installation process and need to complete an assignment or two until you get
the installation sorted out.<a href="chapter1.html#fnref3" class="footnote-back">↩︎</a></p></li>
<li id="fn4"><p>I created this interactive website (<a href="https://allisontheobold.shinyapps.io/R_RStudio_Setup/" class="uri">https://allisontheobold.shinyapps.io/R_RStudio_Setup/</a>) that contains
discussions and activities related to installing and using R and RStudio.<a href="chapter1.html#fnref4" class="footnote-back">↩︎</a></p></li>
<li id="fn5"><p>The need to keep the code
up-to-date as <code>R</code> continues to evolve is one reason that this book is locally
published and that this is the 7<sup>th</sup> time it has been revised in seven years…<a href="chapter1.html#fnref5" class="footnote-back">↩︎</a></p></li>
<li id="fn6"><p>There are ways to read
“.xls” and “.xlsx” files directly into <code>R</code> that we will explore later so you can
also use that format if you prefer.<a href="chapter1.html#fnref6" class="footnote-back">↩︎</a></p></li>
<li id="fn7"><p>Tibbles are an
<code>R</code> object that behaves slightly different from a dataframe, but can be used in
the same way, e.g. a tibble can contain both categorical and quantitative
variables on your <span class="math inline">\(n\)</span> subjects with a name for each variable that is also the
name of each column in a matrix, like what we saw with dataframes.
 Each subject is a row of the data set. The name (supposedly)
is due to the way <em>table</em> sounds in the accent of a particularly influential
developer at RStudio who is from New Zealand.<a href="chapter1.html#fnref7" class="footnote-back">↩︎</a></p></li>
<li id="fn8"><p>We can
assess the shape of the distribution of a variable most easily from a graph, or
we could use a five number summary to asses how different the mean and the
median are.<a href="chapter1.html#fnref8" class="footnote-back">↩︎</a></p></li>
<li id="fn9"><p>The
median, quartiles and whiskers sometimes occur at the same values when there are
many tied observations. If you can’t see all the components of the boxplot,
produce the numerical summary to help you understand what happened.<a href="chapter1.html#fnref9" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="copyright.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="chapter2.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": false,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Greenwood_Book.pdf"],
"toc": {
"collapse": "subsection"
},
"toolbar": {
"position": "fixed"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
